version: '3.9'

services: 
    strapi:
        container_name: strapi
        depends_on:
            - postgres
        image: strapi/strapi
        restart: unless-stopped
        environment:
            DATABASE_CLIENT: postgres
            DATABASE_HOST: postgres
            DATABASE_PORT: 5432
            DATABASE_NAME: strapi
            DATABASE_USERNAME: strapi
            DATABASE_PASSWORD: strapi
        volumes:
            - ./strapi:/srv/app
        ports:
            - '80:1337'

    postgres:
        container_name: postgres
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: strapi
            POSTGRES_USER: strapi
            POSTGRES_PASSWORD: strapi
        volumes:
            - ./postgres-data:/var/lib/postgresql/data